export const PeopleToFollow = [
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
  {
    name: "Olarenwaju Flora",
    image: require("../../assets/images/profilepic.png"),
    campaigns: "42, 324",
  },
];

export const Interests = [
  { name: "Road Construction" },
  { name: "Street" },
  { name: "Library" },
  { name: "Construction" },
  { name: "Street" },
  { name: "Street Lamp" },
  { name: "Street" },
  { name: "Road Construction" },
  { name: "Street" },
  { name: "Construction" },
  { name: "Library" },
  { name: "Library" },
  { name: "Street" },
  { name: "Street Lamp" },
  { name: "Street" },
  { name: "Construction" },
  { name: "Street" },
  { name: "Library" },
  { name: "Street" },
  { name: "Street" },
  { name: "Road Construction" },
  { name: "Street" },
  { name: "Street" },
  { name: "Road Construction" },
];

export const Hashtags = [
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
  { name: "#Ikejaproject", campaign: "42, 324" },
];
